name: Run main tests

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=.

    - name: Handle test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        profile: cover.out
        git-token: ${{ github.ref_name == 'main' && secrets.GH_TOKEN || '' }}
        git-branch: main
        git-repository: andre487/gh-content
        git-file-name: badges/${{ github.repository }}/${{ github.ref_name }}/test-coverage.svg
